name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install cogs dotnet tool
      run: dotnet tool install --global --add-source https://ci.appveyor.com/nuget/cogs/ cogs

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install python dependencies
      run: pip install -r build/requirements.txt


    - name: Install other dependencies
      run: .\build\install-dependencies.ps1
      shell: pwsh
      
    - name: Get file suffix
      id: suffix
      run: if ($env:GITHUB_REF -match 'refs/tags/(.+)') { $Matches[1] } else { (Get-Date -Format "yyyyMMdd") }
      shell: pwsh

    - name: Run build-windows.bat
      run: .\build\build-windows.bat
      shell: cmd

    - name: Copy and rename outputs
      shell: pwsh
      run: |
        mkdir ddi-lifecycle
        xcopy ddi-lifecycle-all-outputs\xsd ddi-lifecycle\xsd /E /I
        xcopy ddi-lifecycle-all-outputs\json ddi-lifecycle\json /E /I
        xcopy ddi-lifecycle-all-outputs\owl ddi-lifecycle\owl /E /I
        $suffix = if ($env:GITHUB_REF -match 'refs/tags/(.+)') { $Matches[1] } else { (Get-Date -Format "yyyyMMdd") }
        $env:suffix = $suffix
        ren ddi-lifecycle ddi-lifecycle-${suffix}
        ren ddi-lifecycle-all-outputs ddi-lifecycle-all-outputs-${suffix}
        7z a -tzip "ddi-lifecycle-all-outputs.zip" "ddi-lifecycle-all-outputs\*"

    - name: Make all outputs artifact
      uses: actions/upload-artifact@v3
      with:
          name: ddi-lifecycle-all-outputs-$env.suffix
          path: ddi-lifecycle-all-outputs-$env.suffix.zip

    - name: Make package artifact
      uses: actions/upload-artifact@v3
      with:
        name: ddi-lifecycle-$env.suffix
        path: ddi-lifecycle-$env.suffix