name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install cogs dotnet tool
      run: dotnet tool install --global --add-source https://ci.appveyor.com/nuget/cogs/ cogs

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install python dependencies
      run: |
        pip install sphinx
        pip install sphinx_rtd_theme
        pip install Pygments


    - name: Install other dependencies
      run: .\build\install-dependencies.ps1
      shell: pwsh

    - name: Run build-windows.bat
      run: .\build\build-windows.bat
      shell: cmd

    - name: Make all outputs artifact
      uses: actions/upload-artifact@v3
      with:
          name: ddi-lifecycle-all-outputs
          path: ddi-lifecycle-all-outputs*.zip

    - name: Make package artifact
      uses: actions/upload-artifact@v3
      with:
        name: ddi-lifecycle
        path: |
          ddi-lifecycle*.zip